### ISSUE TITLE
Vulnerable Code

### ISSUE THREAD

**Issue by davidkevork** [masknetwork/web_node#2]
PHP mysql_* functions are deprecated and no more used and they are vulnerable to SQL injection and none of your code filters the input to protect it from SQL attacks

**Comment by franktabasco** [comment]
You can rewrite all your queries using an ORM. I recommend Eloquent, from Laravel. If you are a big fan of writing plain PHP, you can still install only Eloquent, using composer package manager. 
It's much safer, you can bind your parameters on row queries, or create models that map on sql tables.  https://jenssegers.com/53/using-eloquent-without-laravel

**Comment by masknetwork** [comment]
db.php is included in every single page and the following code is executed before any other query 

foreach($_REQUEST as $key => $value)
		 {
			 $_REQUEST[$key]=str_replace("'", "", $_REQUEST[$key]);
			 $_REQUEST[$key]=str_replace("\"", "", $_REQUEST[$key]);
			 $_REQUEST[$key]=str_replace("\\", "", $_REQUEST[$key]);		
		}

It's a basic SQL injection tool that checks all parameters for sensible characters but it can be extended / customised. No need to rewrite queries. The best anti SQL injection tool is still an application firewall like ModSecurity.

The web node will be installed by end users on all kinds of machines / configurations. Older versions of PHP are still very popular. We prefer not to use frameworks in a security critical project like a cryptocurrency.

**Comment by franktabasco** [comment]
@davidkevork  @masknetwork i think both solutions have pros and cons, but from the bussiness logic point of view, I think installing a webnode should be very easy: just copying or pulling the code on a server. Majority of shared hostings come with PHP in higher versions && installing a LAMP stack on a VPS also comes with higher versions. Puttin the user to also install mod_security - without understanding what the hell is he doing could lead to some trouble. 

I'm not contesting the cleaning of your sqls. It is much easier with an orm. Even to perform your queries inside your app. Most of the ORMs available are very strong and very well mantained. 

But the only problem I see is that - me, as a user - I find it very timeconsuming to install the webnode if I have to do other sysadmin stuff. 

I think it would grow in popularity or help grow in popularity if you can document some steps for a "good practice install" - or even create a docker file (https://www.containership.io/) with a minimum configuration. So, from my point of view the quality of the written code is much less important than the validation of your idea and making it popular. 

The first and simplest step would be to document this "good practice install" so everyone that installs a web_node can be aware of the possible issues.

**Comment by davidkevork** [comment]
@franciscboicu @masknetwork the code does is not necessary to be object oriented. the code can be migrated from mysql_* functions to mysqli_* function which is more secure and better practice and required very little work.

if you take a look at php official website for mysql_* functions http://php.net/manual/en/function.mysql-connect.php they clearly state that the extension was deprecated in PHP 5.5.0 and removed in PHP 7.0.0.

migrating from mysql_ to mysqli_ is easy. all you need to do is to add the extra` i` and pass the $connection parameter.

As PHP 7.0.0 has more speed, you can't use mysql_ functions and thus you can't provide your users faster website/api access and like thus you can gain more users like that.

For ./kernel/dp.php instead of using
foreach($_REQUEST as $key => $value)
{
$_REQUEST[$key]=str_replace("'", "", $_REQUEST[$key]);
$_REQUEST[$key]=str_replace("\"", "", $_REQUEST[$key]);
$_REQUEST[$key]=str_replace("\\", "", $_REQUEST[$key]);		
}
you can simply use
foreach($_REQUEST as $key => $value)
{
$_REQUEST[$key] = mysql_real_escape_string($value);
}

using $_REQUEST[$key]=str_replace("'", "", $_REQUEST[$key]); makes no sense because you are filtering the $key for sql injection and setting it back instead you should filter the $value.

One more issue

 //if ($_SERVER['HTTP_CF_CONNECTING_IP']!="89.149.21.42") die ("Maintainance in progress. Try again in a few hours.");
sharing your ip address to public is not a good practice

**Comment by franktabasco** [comment]
@masknetwork if I fork the project to make improvements, would you consider merging them into master branch if you agree with them?
